/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List books
         * @description Public catalog listing. No authentication, no writes. Returns a page of books in a { data, pagination } envelope.
         */
        get: operations["listBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a book by id
         * @description Public book detail. No authentication, no writes.
         */
        get: operations["getBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Self-register (creates a member)
         * @description Public self-registration. Always creates a `member`; elevated roles are granted only by an admin via POST /users/{id}/roles.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a JWT
         * @description Returns the JWT in the body (android sends it as `Authorization: Bearer`) AND sets it as an `HttpOnly`, `SameSite=Lax` `session` cookie (web; `Secure` is added in production). Protected endpoints accept EITHER the bearer header (which takes precedence) or the cookie.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear the session cookie
         * @description Expires the `session` cookie (`Set-Cookie: session=; Max-Age=0`). Bearer clients simply discard their token; this is a no-op for them.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current authenticated principal */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        /** Delete your own account */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /** Update your own account (email) */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change your own password */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an email with a token
         * @description Public; the token from the verification email authenticates the call.
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password-reset email
         * @description Public. Always returns 202 regardless of whether the email exists (no user enumeration); a reset link is emailed only if the account exists.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset a password with a token
         * @description Public; the token from the reset email authenticates the call.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users (admin only) */
        get: operations["listUsers"];
        put?: never;
        /** Create a user (admin only) */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user (admin only) */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        /** Update a user's email/active flag (admin only) */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign a role to a user (admin only) */
        post: operations["assignRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List loans
         * @description A member sees only their own loans; staff (librarian/admin) see all loans.
         */
        get: operations["listLoans"];
        put?: never;
        /**
         * Borrow a book
         * @description Opens an active loan and flips the book unavailable. Any authenticated user may borrow an available book.
         */
        post: operations["borrowBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loans/{id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Return a borrowed book
         * @description The borrower returns their own loan; staff may return any. Flips the book available again.
         */
        post: operations["returnLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loans/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a returned loan (staff only)
         * @description Staff confirm a returned loan, closing it. Members are forbidden.
         */
        post: operations["approveLoan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rank books for a user's preferences
         * @description Public. Ranks candidate books for the given preferences using the shared decision-tree recommender — the same logic the mobile app runs on-device via the UniFFI binding. Supply `candidates` to rank a specific set, or omit it to rank the server's catalog. No authentication: preferences come from the body, not from stored user data.
         */
        post: operations["recommend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/rooms/{room}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Room message history
         * @description Paginated chat history for a room (oldest first). Any authenticated user may read a room (group chat).
         */
        get: operations["chatHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Group chat WebSocket (upgrade)
         * @description WebSocket endpoint for live group chat (ADR 0006). OpenAPI cannot model the stream itself, so the protocol is documented here; frontends derive the chat DTOs from `ChatSend` and `ChatMessage` below.
         *
         *     Connect: `GET /ws/chat?room=<room>&token=<jwt>` with the standard `Upgrade: websocket` headers. Auth is resolved in order: the `token` query param carries the IAM JWT (browsers cannot set headers on a WS handshake); then `Authorization: Bearer <jwt>` for non-browser clients; then the `session` cookie (web, whose JWT lives in an httpOnly cookie with no JS token available for the query param). Unauthenticated upgrades are rejected with `401` before the protocol switch.
         *
         *     Client → server frames: JSON matching `ChatSend` (`{ body }`). Each is persisted to history and broadcast to every connection in the same room.
         *
         *     Server → client frames: JSON matching `ChatMessage`. Past history is read over REST via `GET /chat/rooms/{room}/messages`.
         */
        get: operations["chatWebSocket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register an FCM device token
         * @description Register (or refresh) an FCM push token for the authenticated user, so the due-date scheduler can reach their device.
         */
        post: operations["registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reminder history
         * @description The authenticated user's reminder history. Reminders are produced by an internal background scheduler (ADR 0006) that periodically scans loan due dates and pushes due-soon/overdue reminders via FCM — it is not a request-driven endpoint, so it has no path of its own.
         */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Book: {
            /** Format: uuid */
            id: string;
            title: string;
            author: string;
            isbn: string;
            shelf: string;
            /** Format: int32 */
            row: number;
            available: boolean;
        };
        Pagination: {
            /**
             * Format: int32
             * @description 1-based page number echoed back.
             */
            page: number;
            /**
             * Format: int32
             * @description Items per page applied (after clamping).
             */
            page_size: number;
            /**
             * Format: int64
             * @description Total number of books across all pages.
             */
            total: number;
            /**
             * Format: int32
             * @description Number of pages at this page_size.
             */
            total_pages: number;
        };
        BookList: {
            data: components["schemas"]["Book"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** @description Flat error body returned by 4xx/5xx responses. */
        Error: {
            /** @description Stable machine-readable error code, e.g. "not_found". */
            code: string;
            /** @description Human-readable explanation. */
            message: string;
        };
        /**
         * @description A user role.
         * @enum {string}
         */
        Role: "admin" | "librarian" | "member";
        Credentials: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthToken: {
            /** @description Signed JWT bearer token. */
            token: string;
            /** @example Bearer */
            token_type: string;
            /**
             * Format: int64
             * @description Token lifetime in seconds.
             */
            expires_in: number;
        };
        /** @description A user record without the password hash. */
        Principal: {
            /** Format: uuid */
            id: string;
            email: string;
            role: components["schemas"]["Role"];
            verified: boolean;
            active: boolean;
        };
        /** @description Admin view of a user (never the password hash). */
        UserSummary: {
            /** Format: uuid */
            id: string;
            email: string;
            role: components["schemas"]["Role"];
            verified: boolean;
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        UserList: {
            data: components["schemas"]["UserSummary"][];
            pagination: components["schemas"]["Pagination"];
        };
        AssignRoleRequest: {
            role: components["schemas"]["Role"];
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            role: components["schemas"]["Role"];
        };
        /** @description Any subset of the updatable fields. */
        UpdateUserRequest: {
            /** Format: email */
            email?: string;
            active?: boolean;
        };
        UpdateMeRequest: {
            /** Format: email */
            email: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string;
        };
        VerifyEmailRequest: {
            token: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            /** Format: password */
            new_password: string;
        };
        /**
         * @description Loan lifecycle status. `borrowed` → `returned` → `approved`. Overdue is derived from `due_at`, not a stored status.
         * @enum {string}
         */
        LoanStatus: "borrowed" | "returned" | "approved";
        BorrowRequest: {
            /** Format: uuid */
            book_id: string;
        };
        Loan: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            book_id: string;
            /** Format: uuid */
            user_id: string;
            status: components["schemas"]["LoanStatus"];
            /** Format: date-time */
            borrowed_at: string;
            /** Format: date-time */
            due_at: string;
            /** Format: date-time */
            returned_at?: string | null;
            /** Format: uuid */
            approved_by?: string | null;
            /** Format: date-time */
            approved_at?: string | null;
        };
        LoanList: {
            data: components["schemas"]["Loan"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** @description What the user likes. Empty arrays mean no preference on that axis. */
        Preferences: {
            preferred_shelves?: string[];
            preferred_authors?: string[];
            /** @default false */
            available_only: boolean;
        };
        RecommendCandidate: {
            /** Format: uuid */
            id: string;
            shelf: string;
            author: string;
            available: boolean;
        };
        RecommendRequest: {
            preferences?: components["schemas"]["Preferences"];
            /** @description Explicit candidates to rank; omit to rank the server catalog. */
            candidates?: components["schemas"]["RecommendCandidate"][];
        };
        RecommendResponse: {
            /** @description Candidate book ids, best match first. */
            ranked: string[];
        };
        /** @description A stored/broadcast chat message (server → client). */
        ChatMessage: {
            /** Format: uuid */
            id: string;
            room: string;
            /** Format: uuid */
            user_id: string;
            body: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @description A message the client sends over the socket (client → server). */
        ChatSend: {
            body: string;
        };
        ChatMessageList: {
            data: components["schemas"]["ChatMessage"][];
            pagination: components["schemas"]["Pagination"];
        };
        /** @enum {string} */
        Platform: "android" | "ios" | "web";
        /**
         * @description Why a reminder fired.
         * @enum {string}
         */
        ReminderKind: "due_soon" | "overdue";
        DeviceRegistration: {
            /** @description FCM registration token. */
            token: string;
            platform: components["schemas"]["Platform"];
        };
        Device: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            token: string;
            platform: components["schemas"]["Platform"];
            /** Format: date-time */
            registered_at: string;
        };
        /** @description A logged due-date reminder. */
        Notification: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            loan_id: string;
            kind: components["schemas"]["ReminderKind"];
            message: string;
            /** Format: date-time */
            created_at: string;
        };
        NotificationList: {
            data: components["schemas"]["Notification"][];
            pagination: components["schemas"]["Pagination"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The gateway is serving. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    listBooks: {
        parameters: {
            query?: {
                /** @description 1-based page number. Clamped to a minimum of 1. */
                page?: number;
                /** @description Items per page. Clamped to the range [1, 100]. */
                page_size?: number;
                /** @description Book-finder filter: narrow to books on this exact shelf label. Combinable with row and with page/page_size. */
                shelf?: string;
                /** @description Book-finder filter: narrow to books in this exact row. Combinable with shelf and with page/page_size. */
                row?: number;
                /** @description Book-finder filter: narrow to books with this exact ISBN. Lets a client resolve a scanned barcode to a book server-side. */
                isbn?: string;
                /** @description Free-text search: case-insensitive substring match over title, author, and ISBN. Combinable with the other filters and pagination. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of books (after any shelf/row/ISBN/text filtering). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookList"];
                };
            };
            /** @description Unexpected backend failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Book id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The book. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book"];
                };
            };
            /** @description No book with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected backend failure. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description The created user. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
            /** @description Invalid email or weak password. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Email already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description A signed bearer token (also set as the `session` cookie via Set-Cookie). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthToken"];
                };
            };
            /** @description Invalid credentials (unknown email or wrong password). */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Refused — you are the last admin. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description The updated principal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Email already in use. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description New password too weak. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not authenticated, or the current password is wrong. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Email verified. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token invalid, expired, or already used. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Accepted (whether or not the email exists). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password reset. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token invalid/expired/used, or the new password is too weak. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authenticated but not an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description The created user. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            /** @description Invalid email or weak password. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authenticated but not an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Email already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authenticated but not an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Refused — would remove the last admin (or yourself). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description The updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authenticated but not an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Email in use, or would lock out the last admin. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    assignRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target user id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignRoleRequest"];
            };
        };
        responses: {
            /** @description The updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authenticated but not an admin. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such user. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listLoans: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of loans. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanList"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    borrowBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BorrowRequest"];
            };
        };
        responses: {
            /** @description The created loan. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such book. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The book is not available to borrow. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    returnLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Loan id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The returned loan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not the owner and not staff. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such loan. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The loan is not in a returnable state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    approveLoan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Loan id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The approved loan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Loan"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authenticated but not staff. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such loan. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The loan is not awaiting approval. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    recommend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Ranked candidate ids, best match first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendResponse"];
                };
            };
        };
    };
    chatHistory: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                /** @description Room key (an event id, a book category, or "ask-a-librarian"). */
                room: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of messages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageList"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    chatWebSocket: {
        parameters: {
            query: {
                /** @description Room key to join. */
                room: string;
                /** @description IAM JWT (the browser-friendly alternative to the Authorization header). */
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols — the WebSocket is established. */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegistration"];
            };
        };
        responses: {
            /** @description The registered device. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
            /** @description Empty/invalid token. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of reminders. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            /** @description Not authenticated. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
