/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List books
         * @description Public catalog listing. No authentication, no writes. Returns a page of books in a { data, pagination } envelope.
         */
        get: operations["listBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Book: {
            /** Format: uuid */
            id: string;
            title: string;
            author: string;
            isbn: string;
            shelf: string;
            /** Format: int32 */
            row: number;
            available: boolean;
        };
        Pagination: {
            /**
             * Format: int32
             * @description 1-based page number echoed back.
             */
            page: number;
            /**
             * Format: int32
             * @description Items per page applied (after clamping).
             */
            page_size: number;
            /**
             * Format: int64
             * @description Total number of books across all pages.
             */
            total: number;
            /**
             * Format: int32
             * @description Number of pages at this page_size.
             */
            total_pages: number;
        };
        BookList: {
            data: components["schemas"]["Book"][];
            pagination: components["schemas"]["Pagination"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The gateway is serving. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    listBooks: {
        parameters: {
            query?: {
                /** @description 1-based page number. Clamped to a minimum of 1. */
                page?: number;
                /** @description Items per page. Clamped to the range [1, 100]. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of books. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookList"];
                };
            };
        };
    };
}
